### ISSUE TITLE
ModuleNotFoundError raised with pytest 7.2.0

### ISSUE THREAD

**Issue by vereszol** [henry0312/pytest-pycodestyle#97]
pytest==7.2.0 no longer depends on py library [1], but pytest-pycodestyle still tries to use it, leading to this error:

```
$ py.test apple.py 
Traceback (most recent call last):
  File "/tmp/myenv/bin/py.test", line 8, in <module>
    sys.exit(console_main())
...
  File "/tmp/myenv/lib/python3.9/site-packages/pytest_pycodestyle.py", line 7, in <module>
    import py.io
ModuleNotFoundError: No module named 'py.io'; 'py' is not a package
```

A workaround is to install `py`, but it would be better to list that package in setup.py install_requires.

[1] https://docs.pytest.org/en/stable/changelog.html

**Comment by henry0312** [comment]
Thank you for report!

**Comment by vereszol** [comment]
Thanks for the quick fix.
When are you going to release the next version?
